### ISSUE TITLE
Developement environement 

### ISSUE THREAD

**Issue by poquirion** [c3g/project_tracking#12]
Can be deployed with pip
Need to run on AllianceCan hpc

has a _clear_db_ function that flush all exiting data

**Comment by poquirion** [comment]
@paulstretenowich 

The following command can flush the db, event when the server is running, just make sure that the db_uri is well set
```bash
flask  --app project_tracking init-db --flush --db_uri "sqlite:////tmp/my_test_db.sql" 
```.

I have fixed the installation and it can now be installed on Beluga. I suggest that you install and test the server on a login node's localscratch.

```
mkdir /localscratch/paul
cd  /localscratch/paul
git clone  git@github.com:c3g/project_tracking.git
git checkout dev
cd project_tracking
python -m venv venv
source ./venv/bin/activate
pip install  --upgrade pip
pip install -e  .
# Seting the db url is optiopnal, the default will be in the app installation folder
export C3G_SQLALCHEMY_DATABASE_URI="sqlite:////tmp/my_test_db.sql" 
# initialyse the db
flask  --app project_tracking init-db
# run the app 
flask --app project_tracking --debug run
```

**Comment by paulstretenowich** [comment]
Between `pip install  --upgrade pip` and `pip install -e  .` there is a `cd ..` missing
